### ISSUE TITLE
can websocket stream be used for receiving cash data?

### ISSUE THREAD

**Issue by LiangChenAC** [dgrr/binance-futures-sdk#3]
I read the websocket API docs between cash and futures, it seems no differences except host IP and port. When I changed the IP and port, the program connects well, but it fails at throwing 'stream truncated' error when trying to subscribe.

**Comment by dgrr** [comment]
Yes. Same with the coin-margined, if the events are the same, you just need to change the API host.

**Comment by LiangChenAC** [comment]
Is it the same for  spot-margined?

**Comment by dgrr** [comment]
Spot changes a little, they have different apis and reponses. You can try.

**Comment by LiangChenAC** [comment]
> Spot changes a little, they have different apis and reponses. You can try.

Thanks. I have figured out where it went wrong. It seems when doing ws_.async_connect for spot-margined contracts, you need to change "/ws/" to "/ws/"+yourchannels. If you put default channel like "/ws/"+"btcusdt@depth" and then subscribed to multiple other channels, the errors such as "the websocket handshake was declined by the remote peer" will disappear.

I don't know why binance spot-margined wants a default channel though.

**Comment by dgrr** [comment]
No. I think the problem might be because you need to use the `/ws`, not the `/ws/`. The difference relies on the last `/`.

**Comment by LiangChenAC** [comment]
> No. I think the problem might be because you need to use the `/ws`, not the `/ws/`. The difference relies on the last `/`.

This is exactly the difference. Thanks for pointing it out.
